// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiieilnqwfhuldxnaugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9paWVpbG5xd2ZodWxkeG5hdWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDA1NjUsImV4cCI6MjA1NjkxNjU2NX0.wJKETyvTbegQOySDeO9eo4ycYjDuMzCUIN1s37qMMBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);